// Builds one browsable index.html pairing every view across the captured
// languages side by side.
//
//   node scripts/demo/gallery.mjs <output-dir>
//
// Languages come from DEMO_LANGS (default "en de"); each must be a subdirectory
// of <output-dir> holding the PNGs.
import { writeFileSync } from 'node:fs'

const outDir = process.argv[2] ?? 'demo-screenshots'
const langs = (process.env.DEMO_LANGS ?? 'en de').split(/\s+/).filter(Boolean)
const langLabel = { en: 'English', de: 'Deutsch' }

const views = [
  ['01-sign-in', 'Sign in', 'public'],
  ['02-lost-password', 'Lost password', 'public'],
  ['03-download-gallery', 'Download — gallery', 'public'],
  ['04-download-list', 'Download — file list', 'public'],
  ['05-download-locked', 'Download — password required', 'public'],
  ['10-dashboard', 'Dashboard', 'member'],
  ['11-compose', 'New transfer', 'member'],
  ['12-compose-filled', 'New transfer — files staged', 'member'],
  ['13-account', 'Account & API keys', 'member'],
  ['14-users', 'Users (admin)', 'member'],
  ['15-new-user', 'New user (admin)', 'member'],
  ['20-guest-upload', 'Guest upload', 'guest']
]

const row = ([file, title, kind]) => `
  <section id="${file}">
    <h2>${title} <span class="kind kind-${kind}">${kind}</span></h2>
    <div class="grid">
      ${langs.map(lang => `
        <figure>
          <a href="${lang}/${file}.png" target="_blank" rel="noreferrer">
            <img src="${lang}/${file}.png" alt="${title} (${lang})" loading="lazy">
          </a>
          <figcaption>${langLabel[lang] ?? lang}</figcaption>
        </figure>`).join('')}
    </div>
  </section>`

writeFileSync(`${outDir}/index.html`, `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>LokalTransfer — demo screenshots</title>
<style>
  :root { color-scheme: light dark; --bg:#f5f5f7; --card:#fff; --text:#1c1c1e; --muted:#6b6b70; --accent:#CC0030; }
  @media (prefers-color-scheme: dark) {
    :root { --bg:#1c1c1e; --card:#2c2c2e; --text:#f2f2f7; --muted:#aeaeb2; --accent:#DE0F3B; }
  }
  * { box-sizing: border-box; }
  body { margin:0; padding:32px; background:var(--bg); color:var(--text);
         font:15px/1.5 Inter, ui-sans-serif, system-ui, -apple-system, sans-serif; }
  header { max-width:1400px; margin:0 auto 32px; }
  h1 { margin:0 0 4px; font-size:28px; letter-spacing:-0.01em; }
  p.lead { margin:0; color:var(--muted); }
  nav { max-width:1400px; margin:0 auto 32px; display:flex; flex-wrap:wrap; gap:8px; }
  nav a { padding:4px 10px; border-radius:999px; background:var(--card); color:var(--text);
          text-decoration:none; font-size:13px; }
  section { max-width:1400px; margin:0 auto 40px; }
  h2 { font-size:17px; margin:0 0 12px; display:flex; align-items:center; gap:10px; }
  .kind { font-size:11px; font-weight:500; text-transform:uppercase; letter-spacing:0.04em;
          padding:2px 8px; border-radius:999px; background:var(--card); color:var(--muted); }
  .kind-public { color:var(--accent); }
  .grid { display:grid; grid-template-columns:repeat(${langs.length}, 1fr); gap:16px; }
  figure { margin:0; }
  img { width:100%; height:auto; display:block; border-radius:12px; background:var(--card);
        box-shadow:0 20px 25px -5px rgb(0 0 0 / .1), 0 8px 10px -6px rgb(0 0 0 / .1); }
  figcaption { margin-top:8px; font-size:13px; color:var(--muted); }
</style>
</head>
<body>
<header>
  <h1>LokalTransfer — demo screenshots</h1>
  <p class="lead">Generated by <code>pnpm demo:screenshots</code> from a throwaway seeded instance.</p>
</header>
<nav>${views.map(([f, t]) => `<a href="#${f}">${t}</a>`).join('')}</nav>
${views.map(row).join('')}
</body>
</html>
`)

console.log(`wrote ${outDir}/index.html`)
