import { describe, expect, it } from 'vitest'
import { join, sep } from 'node:path'
import {
  generateStoredName,
  resolveStoredFile,
  storageRoot,
  transferDir
} from '../../server/utils/storage'
import { TEST_STORAGE } from '../setup/testConfig'

// The storage layer is the only place a request-supplied value could become a
// filesystem path, so its refusals are the interesting part.

describe('storageRoot', () => {
  it('resolves to an absolute path', () => {
    expect(storageRoot()).toBe(TEST_STORAGE)
  })
})

describe('transferDir', () => {
  it('gives each transfer its own directory under transfers/', () => {
    expect(transferDir(42)).toBe(join(TEST_STORAGE, 'transfers', '42'))
  })
})

describe('generateStoredName', () => {
  it('is hex with no path characters in it', () => {
    for (let i = 0; i < 50; i++) {
      const name = generateStoredName()
      expect(name).toMatch(/^[0-9a-f]+$/)
      expect(name).not.toContain('/')
      expect(name).not.toContain('.')
    }
  })

  it('does not collide', () => {
    const names = new Set(Array.from({ length: 500 }, () => generateStoredName()))
    expect(names.size).toBe(500)
  })
})

describe('resolveStoredFile', () => {
  it('resolves a normal stored name inside the transfer directory', () => {
    const name = generateStoredName()
    expect(resolveStoredFile(7, name)).toBe(join(TEST_STORAGE, 'transfers', '7', name))
  })

  it('refuses to escape the transfer directory', () => {
    // Stored names are generated by this module, so reaching here means the
    // database itself was tampered with. The check turns an arbitrary file read
    // into a null.
    for (const attempt of [
      '../8/secret',
      '../../../../etc/passwd',
      `..${sep}..${sep}config`,
      '/etc/passwd'
    ]) {
      expect(resolveStoredFile(7, attempt), attempt).toBeNull()
    }
  })

  it('refuses a sibling directory that merely shares a prefix', () => {
    // The trailing-separator subtlety: without it, transfers/1extra would pass a
    // naive startsWith('transfers/1') check.
    expect(resolveStoredFile(1, '../1extra/file')).toBeNull()
  })

  it('allows a name that merely contains dots', () => {
    expect(resolveStoredFile(7, 'a.b.c')).toBe(join(TEST_STORAGE, 'transfers', '7', 'a.b.c'))
  })
})
