import { promises as fs } from 'node:fs'
import { isAbsolute, join, resolve, sep } from 'node:path'
import { randomBytes } from 'node:crypto'
import type { H3Event } from 'h3'
import { logger } from './logger'

// Where uploaded files live on disk.
//
// The storage root is deliberately outside `public/`: nothing under it is served
// statically, so a file is only ever reachable through the download handler,
// which checks the transfer's token and expiry first. Putting uploads in
// `public/` would make every file world-readable to anyone who guessed the path,
// and would quietly outlive the expiry rules.
//
// Layout is one directory per transfer:
//   <root>/transfers/<transfer id>/<random stored name>
// which makes deleting an expired transfer a single recursive remove, and means
// a stray file can always be traced back to a row.

/** Absolute path of the storage root, resolved from runtimeConfig. */
export function storageRoot(event?: H3Event): string {
  const config = useRuntimeConfig(event)
  const configured = String(config.storagePath || './storage')
  // A relative path is resolved against the working directory, which is the
  // project root in dev and the deployment directory in production.
  return isAbsolute(configured) ? configured : resolve(process.cwd(), configured)
}

/** Absolute path of one transfer's directory. */
export function transferDir(transferId: number, event?: H3Event): string {
  return join(storageRoot(event), 'transfers', String(transferId))
}

/** Create a transfer's directory if it doesn't exist yet. */
export async function ensureTransferDir(transferId: number, event?: H3Event): Promise<string> {
  const dir = transferDir(transferId, event)
  await fs.mkdir(dir, { recursive: true })
  return dir
}

/**
 * Generate the on-disk name for an upload.
 *
 * The original filename never touches the filesystem — it is kept in the
 * database and only reattached in the `Content-Disposition` header on the way
 * out. That removes path traversal, reserved Windows names, unicode
 * normalisation collisions and case-insensitive overwrites as a class of
 * problem, rather than trying to sanitise them one by one.
 */
export function generateStoredName(): string {
  return randomBytes(24).toString('hex')
}

/**
 * Resolve a stored file to an absolute path, refusing anything that escapes its
 * transfer's directory.
 *
 * Stored names are generated by this module, so a traversal attempt would mean
 * the database itself was tampered with. The check costs nothing and turns that
 * from an arbitrary file read into a 404.
 */
export function resolveStoredFile(
  transferId: number,
  storedName: string,
  event?: H3Event
): string | null {
  const dir = transferDir(transferId, event)
  const full = resolve(dir, storedName)

  // The trailing separator matters: without it, `/storage/transfers/1extra`
  // would pass a plain `startsWith('/storage/transfers/1')` check.
  if (full !== dir && !full.startsWith(dir + sep)) {
    logger.warn('Rejected stored file path outside its transfer directory', {
      transferId,
      storedName
    })
    return null
  }

  return full
}

/** Remove a transfer's directory and everything in it. Safe to call twice. */
export async function removeTransferDir(transferId: number, event?: H3Event): Promise<void> {
  const dir = transferDir(transferId, event)
  try {
    await fs.rm(dir, { recursive: true, force: true })
  } catch (error) {
    // Logged rather than thrown: cleanup runs over many transfers, and one
    // undeletable directory shouldn't stop the rest from being processed.
    logger.error('Failed to remove transfer directory', { dir, error })
  }
}

/** Delete a single stored file, ignoring the case where it is already gone. */
export async function removeStoredFile(
  transferId: number,
  storedName: string,
  event?: H3Event
): Promise<void> {
  const full = resolveStoredFile(transferId, storedName, event)
  if (!full) return

  try {
    await fs.unlink(full)
  } catch (error) {
    // A file that is already gone is the expected case when a sweep is retried.
    if ((error as NodeJS.ErrnoException)?.code !== 'ENOENT') {
      logger.error('Failed to remove stored file', { full, error })
    }
  }
}

/** Whether a stored file is actually present on disk. */
export async function storedFileExists(
  transferId: number,
  storedName: string,
  event?: H3Event
): Promise<boolean> {
  const full = resolveStoredFile(transferId, storedName, event)
  if (!full) return false

  try {
    const stats = await fs.stat(full)
    return stats.isFile()
  } catch {
    return false
  }
}
